### PR TITLE
Observable fix

### LINKED ISSUE #585: PropertyPresetManager overrides the displayname
When setting a property using a preset the display name gets set to the display name to the was set to the property when the preset was created. 
This is especially bad for Workspace and Application level presets. 

**Steps to reproduce**
1. Add a background processor
2. Create a workspace or application preset on `Color 1`
3. Set `Color 2` using the preset from `Color 1`

Edit: Added steps to reproduce

### PR DESCRIPTION
**Pull request by petersteneteg**
Observable no longer makes it observers observe its copies

i.e. if widget w observes property a and one creates a clone of a called b. The widget w will not anymore automatically observe both a and b as was previously the case. 

closes #585

### CODE REVIEW

**Review by r-englund — APPROVED** [review]

File: include/inviwo/core/util/observer.h [hunk 1]
```diff
@@ -182,10 +182,28 @@ template <typename T>
...
-    Observable<T>& operator=(Observable<T>&& other);
+
+    /**
+     * This operation does nothing. We will not touch the observers of other
+     */
+
     Observable<T>& operator=(const Observable<T>& other);
+
+    /**
+     * This operation will remove all observers of this, amek make all observers of other observe this
```
Comment (ResearchDaniel) [inline include/inviwo/core/util/observer.h]: Typo "amek"

File: include/inviwo/core/util/observer.h [hunk 2]
```diff
@@ -182,10 +182,28 @@ template <typename T>
...
+    /**
+     * This operation will remove all observers from other and add them to this.
+     */
     Observable(Observable<T>&& other);
-    Observable<T>& operator=(Observable<T>&& other);
+
+    /**
+     * This operation does nothing. We will not touch the observers of other
+     */
+
```
Comment (ResearchDaniel) [inline include/inviwo/core/util/observer.h]: remove empty line

**Review by ResearchDaniel — APPROVED** [review]
Minor comments
