### PR TITLE
Fixing fragment renderer resize

### LINKED ISSUE #955: Crash in Rasterization Renderer when disconnecting optional background inport
Probably caused by `imageInport_->getData()` return nullptr in the code refrenced below: 

https://github.com/inviwo/inviwo/blob/d1749ba220ba089cc78391da222461e38ad40bd4/modules/meshrenderinggl/src/processors/rasterizationrenderer.cpp#L114-L115

### PR DESCRIPTION
**Pull request by AnkeAnke**
Fixing rasterization renderer crash on background removal.

### CODE REVIEW

**Review by r-englund — DISMISSED** [review]

File: modules/meshrenderinggl/src/processors/rasterizationrenderer.cpp [hunk 1]
```diff
@@ -111,8 +111,12 @@ RasterizationRenderer::RasterizationRenderer()
 
     flrReload_ = flr_.onReload([this]() { invalidate(InvalidationLevel::InvalidResources); });
 
-    imageInport_->onChange(
-        [this]() { intermediateImage_.setDimensions(imageInport_->getData()->getDimensions()); });
+    imageInport_->onChange([this]() {
+        if (imageInport_->hasData())
```
Comment (petersteneteg) [inline modules/meshrenderinggl/src/processors/rasterizationrenderer.cpp]: We always use braces with ifs...

Comment (petersteneteg) [reply modules/meshrenderinggl/src/processors/rasterizationrenderer.cpp]: thanks, that makes me happy :)

**Review by petersteneteg — APPROVED** [review]
