### PR TITLE
Feature/misc fixes

### LINKED ISSUE #1394: [BUG]: Animation does not stop when closing Animation Editor
### Problem description

Closing the Animation Editor while playing back an animation will not stop the animation.

### Inviwo version

c570dac

### PR DESCRIPTION
**Pull request by martinfalk**
Fixes #1394 
* MainWindow / Qt
    + fixed closeEvent handling
    + prevent PythonEditor asking twice to save changes
* Python
    + `__repr__` for `DataFormatBase` was not defined properly, which broke `str(inviwopy.data.formats)`
* Animation Editor
    + playback stops when closing the editor
    + default interpolation for scalars changed to `linear` (was `constant`)

### CODE REVIEW

File: modules/cimg/src/cimgutils.cpp [hunk 1]
```diff
@@ -169,6 +169,21 @@ namespace inviwo {
 
 namespace cimgutil {
 
+namespace detail {
+
+cimgutil::InterpolationType convertInterpolationType(inviwo::InterpolationType type) {
```
Comment (ResearchDaniel) [inline modules/cimg/src/cimgutils.cpp]: Nit
```suggestion
cimgutil::InterpolationType toCImgInterpolationType(inviwo::InterpolationType type) {
```

**Review by ResearchDaniel — DISMISSED** [review]

File: modules/animation/include/modules/animation/datastructures/valuekeyframesequence.h [hunk 2]
```diff
@@ -69,6 +70,16 @@ struct DefaultInterpolationCreator {
     }
 };
 
+template <typename T>
```
Comment (ResearchDaniel) [inline modules/animation/include/modules/animation/datastructures/valuekeyframesequence.h:73]: Seems like a useful concept in other places. Do we want to put these in, for example, util/concepts.h?

File: apps/inviwo/inviwo.cpp [hunk 3]
```diff
@@ -79,6 +80,11 @@ int main(int argc, char** argv) {
     inviwo::utilqt::setStyleSheetFile(":/stylesheets/inviwo.qss");
     inviwoApp.setUILocale(inviwo::utilqt::getCurrentStdLocale());
 
+    QPalette palette(QGuiApplication::palette());
+    palette.setColor(QPalette::Link, QColor("#268BD2"));
+    palette.setColor(QPalette::LinkVisited, QColor("#268BD2"));
+    QGuiApplication::setPalette(palette);
```
Comment (petersteneteg) [inline apps/inviwo/inviwo.cpp]: Move into a function, utilqt::configurePalatte

**Review by petersteneteg — DISMISSED** [review]

**Review by ResearchDaniel — APPROVED** [review]
