### PR TITLE
shader refactor

### LINKED ISSUE #84: GLSL compile error when using extensions
GLSL specification requires that only `#version` directive is before `#extension` directive. However, we include other defines in between, for example #define MAX_PROGRAM_LOOP_COUNT in `void OpenGLCapabilities::rebuildGLSLHeader()`

Tested on Windows with nvidia graphics card. Could not reproduce on Mac

The error is produced when using `ShaderObject::addShaderExtension`
Example:
```
ShaderObject* fragObj = shader->getFragmentShaderObject();
fragObj->addShaderExtension("GL_EXT_shader_image_load_store", true);
```

### LINKED ISSUE #331: Shader.cpp: GCC6 compile error
```
In file included from /usr/include/x86_64-linux-gnu/c++/6/bits/c++allocator.h:33:0,
                 from /usr/include/c++/6/bits/allocator.h:46,
                 from /usr/include/c++/6/string:41,
                 from /home/jochen/git-source/inviwo/modules/opengl/include/modules/opengl/inviwoopengl.h:51,
                 from /home/jochen/git-source/inviwo/modules/opengl/include/modules/opengl/shader/shader.h:34,
                 from /home/jochen/git-source/inviwo/modules/opengl/src/shader/shader.cpp:30:
/usr/include/c++/6/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>; _Args = {const std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>&}; _Tp = std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>]’:
/usr/include/c++/6/bits/alloc_traits.h:475:4:   required from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>; _Args = {const std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>&}; _Tp = std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment> >]’
/usr/include/c++/6/bits/hashtable_policy.h:1953:37:   required from ‘std::__detail::_Hashtable_alloc<_NodeAlloc>::__node_type* std::__detail::_Hashtable_alloc<_NodeAlloc>::_M_allocate_node(_Args&& ...) [with _Args = {const std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>&}; _NodeAlloc = std::allocator<std::__detail::_Hash_node<std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>, true> >; std::__detail::_Hashtable_alloc<_NodeAlloc>::__node_type = std::__detail::_Hash_node<std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>, true>]’
/usr/include/c++/6/bits/hashtable_policy.h:180:58:   required from ‘std::__detail::_AllocNode<_NodeAlloc>::__node_type* std::__detail::_AllocNode<_NodeAlloc>::operator()(_Arg&&) const [with _Arg = const std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>&; _NodeAlloc = std::allocator<std::__detail::_Hash_node<std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>, true> >; std::__detail::_AllocNode<_NodeAlloc>::__node_type = std::__detail::_Hash_node<std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>, true>]’
/usr/include/c++/6/bits/hashtable.h:1681:18:   required from ‘std::pair<typename std::__detail::_Hashtable_base<_Key, _Value, _ExtractKey, _Equal, _H1, _H2, _Hash, _Traits>::iterator, bool> std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_M_insert(_Arg&&, const _NodeGenerator&, std::true_type) [with _Arg = const std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>&; _NodeGenerator = std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>, true> > >; _Key = inviwo::ShaderType; _Value = std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>; _Alloc = std::allocator<std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment> >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<inviwo::ShaderType>; _H1 = std::hash<inviwo::ShaderType>; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; typename std::__detail::_Hashtable_base<_Key, _Value, _ExtractKey, _Equal, _H1, _H2, _Hash, _Traits>::iterator = std::__detail::_Node_iterator<std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>, false, true>; std::true_type = std::integral_constant<bool, true>]’
/usr/include/c++/6/bits/hashtable_policy.h:713:55:   required from ‘std::__detail::_Insert_base<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__ireturn_type std::__detail::_Insert_base<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::insert(const value_type&) [with _Key = inviwo::ShaderType; _Value = std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>; _Alloc = std::allocator<std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment> >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<inviwo::ShaderType>; _H1 = std::hash<inviwo::ShaderType>; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; std::__detail::_Insert_base<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__ireturn_type = std::pair<std::__detail::_Node_iterator<std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>, false, true>, bool>; std::__detail::_Insert_base<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::value_type = std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>]’
/usr/include/c++/6/bits/unordered_map.h:550:31:   required from ‘std::pair<typename std::_Hashtable<_Key, std::pair<const _Key, _Tp>, _Alloc, std::__detail::_Select1st, _Pred, _Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::__detail::__is_noexcept_hash<_Key, _Hash> > >::value, false, true> >::iterator, bool> std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::insert(const value_type&) [with _Key = inviwo::ShaderType; _Tp = inviwo::Shader::ShaderAttachment; _Hash = std::hash<inviwo::ShaderType>; _Pred = std::equal_to<inviwo::ShaderType>; _Alloc = std::allocator<std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment> >; typename std::_Hashtable<_Key, std::pair<const _Key, _Tp>, _Alloc, std::__detail::_Select1st, _Pred, _Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::__detail::__is_noexcept_hash<_Key, _Hash> > >::value, false, true> >::iterator = std::__detail::_Node_iterator<std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>, false, true>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::value_type = std::pair<const inviwo::ShaderType, inviwo::Shader::ShaderAttachment>]’
/home/jochen/git-source/inviwo/modules/opengl/src/shader/shader.cpp:111:95:   required from here
/usr/include/c++/6/ext/new_allocator.h:120:4: error: use of deleted function ‘constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const inviwo::ShaderType; _T2 = inviwo::Shader::ShaderAttachment]’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/6/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6/bits/char_traits.h:39,
                 from /usr/include/c++/6/string:40,
                 from /home/jochen/git-source/inviwo/modules/opengl/include/modules/opengl/inviwoopengl.h:51,
                 from /home/jochen/git-source/inviwo/modules/opengl/include/modules/opengl/shader/shader.h:34,
                 from /home/jochen/git-source/inviwo/modules/opengl/src/shader/shader.cpp:30:
/usr/include/c++/6/bits/stl_pair.h:288:17: note: ‘constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const inviwo::ShaderType; _T2 = inviwo::Shader::ShaderAttachment]’ is implicitly deleted because the default definition would be ill-formed:
       constexpr pair(const pair&) = default;
                 ^~~~
/usr/include/c++/6/bits/stl_pair.h:288:17: error: use of deleted function ‘inviwo::Shader::ShaderAttachment::ShaderAttachment(const inviwo::Shader::ShaderAttachment&)’
In file included from /home/jochen/git-source/inviwo/modules/opengl/src/shader/shader.cpp:30:0:
/home/jochen/git-source/inviwo/modules/opengl/include/modules/opengl/shader/shader.h:62:9: note: declared here
         ShaderAttachment(const ShaderAttachment &) = delete;
         ^~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by petersteneteg**
OpenGL: various cleanup and refactoring, added a addInDeclaration similar to addOutDeclaration, closes #331, closes #84, closes https://github.com/inviwo/inviwo-dev/issues/1989 https://github.com/inviwo/inviwo-dev/issues/998

### CODE REVIEW

**Review by martinfalk — APPROVED** [review]
nice work

File: modules/opengl/src/openglcapabilities.cpp [hunk 1]
```diff
@@ -41,6 +41,8 @@
 
 namespace inviwo {
 
+// Or minimal opengl version is 3.3 and glsl version 330
```
Comment (ResearchDaniel) [inline modules/opengl/src/openglcapabilities.cpp:44]: Our

File: modules/opengl/include/modules/opengl/shader/shaderobject.h [hunk 2]
```diff
@@ -79,41 +96,89 @@ class IVW_MODULE_OPENGL_API ShaderObject {
...
+    void clearInDeclarations();
+    const std::vector<InDeclaration>& getInDeclarations() const;
+
+    /**
+     * Adds the default fragment out declarations to the list of out declarations.
+     * This function is automatically called in the constructor for a fragment shader.
+     * If clearOutDeclarations is called then they will be removed and one would have to
+     * manually call this function to re-add them if needed.
+     */
+    void addStandardFragmentOutDeclarations();
```
Comment (ResearchDaniel) [inline modules/opengl/include/modules/opengl/shader/shaderobject.h:165]: Mention what standard means in our case, i.e.     
```
addOutDeclaration("FragData0", 0);
addOutDeclaration("PickingData", 1);
```
Ideally, this would also be mentioned in the constructor/class documentation

File: modules/opengl/include/modules/opengl/shader/shaderobject.h [hunk 3]
```diff
@@ -79,41 +96,89 @@ class IVW_MODULE_OPENGL_API ShaderObject {
...
 
-    std::pair<std::string, unsigned int> resolveLine(size_t line) const;
+    /**
+     * Adds the default vertex in declarations to the list of in declarations.
+     * This function is automatically called in the constructor for a vertex shader.
+     * If clearInDeclarations is called then they will be removed and one would have to
+     * manually call this function to re-add them if needed.
+     */
+    void addStandardVertexInDeclarations();
```
Comment (ResearchDaniel) [inline modules/opengl/include/modules/opengl/shader/shaderobject.h:178]: Mention what standard means in our case:
vec4 in_Vertex = 0
vec3 in_Normal = 1
vec4 in_Color = 2
vec3 in_TexCoord = 3;

Ideally, this would also be mentioned in the constructor/class documentation

**Review by ResearchDaniel — APPROVED** [review]
Nice! Sime minor comments
Should we say something in the changelog about the switch to 3.3?

File: modules/opengl/src/openglcapabilities.cpp (hunk 1 above)
Comment (petersteneteg) [reply modules/opengl/src/openglcapabilities.cpp:44]: We required 3.3 before also... I just had it wrong in the readme...
