### PR TITLE
OpenGL: Enforce specification of vertex shader since it otherwise res…

### LINKED ISSUE #322: Mac: INVALID_OPERATION when using ImageGLProcessor
Processors based on ImageGLProcessor, for example Image Grayscale, produces invalid operation OpenGL error on line 83:
`utilgl::activateTargetAndCopySource(outport_, inport_, ImageType::ColorOnly);`
which traces to 
line 180 in imagegl.cpp:
`    target->activateBuffer(ImageType::AllLayers);
`
Output from processor is invalid after the error has occurred.

**Steps to reproduce**
Open a workspace including an image source, grayscale and canvas on Mac.

**Environment information**
* Operating System:
Mac OSX High Sierra 10.13.6
Intel Iris Graphics 550

### PR DESCRIPTION
**Pull request by ResearchDaniel**
…ults in undefined behavior according to OpenGL specifications. Closes #322

### CODE REVIEW

File: modules/opengl/src/shader/shader.cpp [hunk 1]
```diff
@@ -38,6 +38,9 @@ namespace inviwo {
 
 Shader::Shader(const std::vector<std::pair<ShaderType, std::string>> &items, Build buildShader)
     : id_{glCreateProgram()}, warningLevel_{UniformWarning::Ignore} {
+    if (std::find_if(std::begin(items), std::end(items), [](const auto& item) { return item.first == ShaderType::Vertex;}) == std::end(items)) {
+        throw Exception("Vertex shader required, provide for example img_identity.vert");
```
Comment (petersteneteg) [inline modules/opengl/src/shader/shader.cpp]: this will leak the program....

File: modules/basegl/src/processors/imageprocessing/imageglprocessor.cpp [hunk 2]
```diff
@@ -47,7 +47,7 @@ ImageGLProcessor::ImageGLProcessor(std::shared_ptr<const ShaderResource> fragmen
     , dataFormat_(nullptr)
     , swizzleMask_(swizzlemasks::rgba)
     , internalInvalid_(false)
-    , shader_({{ShaderType::Fragment, fragmentShader}},
+    , shader_({{ShaderType::Vertex, utilgl::findShaderResource("img_identity.vert")}, {ShaderType::Fragment, fragmentShader}},
```
Comment (petersteneteg) [inline modules/basegl/src/processors/imageprocessing/imageglprocessor.cpp]: would be nicer to just use a StringShaderResource here...

File: modules/opengl/src/shader/shader.cpp (hunk 1 above)
Comment (ResearchDaniel) [reply modules/opengl/src/shader/shader.cpp]: Good catch. Wrapped the id in a scoped variable

File: modules/basegl/src/processors/imageprocessing/imageglprocessor.cpp (hunk 2 above)
Comment (ResearchDaniel) [reply modules/basegl/src/processors/imageprocessing/imageglprocessor.cpp]: Replaced it with a StringShaderResource.

File: modules/opengl/src/shader/shader.cpp (hunk 1 above)
Comment (martinfalk) [reply modules/opengl/src/shader/shader.cpp]: This won't work as intended! In principle one can define multiple vertex shaders. But they must contain exactly one main function when combined... I'd assume there will be a GLSL link error due to missing main.

File: modules/opengl/src/shader/shader.cpp [hunk 3]
```diff
@@ -97,11 +106,11 @@ Shader::Shader(const Shader &rhs) : id_{glCreateProgram()}, warningLevel_{rhs.wa
     ShaderManager::getPtr()->registerShader(this);
 }
 
-Shader::Shader(Shader &&rhs) : id_{rhs.id_}, ready_(rhs.ready_), warningLevel_{rhs.warningLevel_} {
+Shader::Shader(Shader &&rhs) : ready_(rhs.ready_), warningLevel_{rhs.warningLevel_} {
 
     ShaderManager::getPtr()->unregisterShader(&rhs);
-
-    rhs.id_ = 0;
+    prog_ = rhs.prog_;
```
Comment (martinfalk) [inline modules/opengl/src/shader/shader.cpp]: there is a leak here! `this->prog_` is already initialized and has a program. Either you delete that program first or swap `prog_` with `rhs.prog_`

File: modules/opengl/src/shader/shader.cpp [hunk 4]
```diff
@@ -118,9 +127,9 @@ Shader::Shader(Shader &&rhs) : id_{rhs.id_}, ready_(rhs.ready_), warningLevel_{r
 Shader &Shader::operator=(const Shader &that) {
     if (this != &that) {
         bool needRegister = false;
-        if (id_ == 0) {
+        if (prog_.id == 0) {
```
Comment (martinfalk) [inline modules/opengl/src/shader/shader.cpp]: why would `prog_.id` ever be zero?

File: modules/opengl/src/shader/shader.cpp (hunk 3 above)
Comment (martinfalk) [inline modules/opengl/src/shader/shader.cpp]: What about `ShaderManager::getPtr()->unregisterShader(this);` ?

See destructor and move assignment.

**Review by martinfalk — CHANGES_REQUESTED** [review]

File: modules/opengl/src/shader/shader.cpp (hunk 1 above)
Comment (ResearchDaniel) [reply modules/opengl/src/shader/shader.cpp]: I think that would be a different error. Here we just check that one did not miss providing a vertex shader. I guess we could add a search for a main function but it would make it a bit more complicated and a bit out of scope for the PR?

File: modules/opengl/src/shader/shader.cpp (hunk 3 above)
Comment (ResearchDaniel) [reply modules/opengl/src/shader/shader.cpp]: This is the same behavior as before. I assumed that  `ShaderManager::getPtr()->unregisterShader(&rhs);` above deleted the program. Will double check

Comment (ResearchDaniel) [reply modules/opengl/src/shader/shader.cpp]: So I checked and it does not seem remove the program in that way. Will adjust the ScopedShaderProgram

File: modules/opengl/src/shader/shader.cpp (hunk 4 above)
Comment (ResearchDaniel) [reply modules/opengl/src/shader/shader.cpp]: Unlikely, but could be error during creation or moved beforehand. Not part of the PR at least :)

File: modules/opengl/src/shader/shader.cpp (hunk 3 above)
Comment (ResearchDaniel) [reply modules/opengl/src/shader/shader.cpp]: Fixed it

Comment (ResearchDaniel) [reply modules/opengl/src/shader/shader.cpp]: Not necessary in move constructor

**Comment by ResearchDaniel** [comment]
@petersteneteg @martinfalk I think that I adjusted all the comments

File: modules/opengl/src/shader/shader.cpp [hunk 5]
```diff
@@ -97,11 +112,11 @@ Shader::Shader(const Shader &rhs) : id_{glCreateProgram()}, warningLevel_{rhs.wa
     ShaderManager::getPtr()->registerShader(this);
 }
 
-Shader::Shader(Shader &&rhs) : id_{rhs.id_}, ready_(rhs.ready_), warningLevel_{rhs.warningLevel_} {
+Shader::Shader(Shader &&rhs)
+    : prog_{rhs.prog_.id}, ready_(rhs.ready_), warningLevel_{rhs.warningLevel_} {
```
Comment (petersteneteg) [inline modules/opengl/src/shader/shader.cpp]: This should be done by the wapper class

File: modules/opengl/src/shader/shader.cpp [hunk 6]
```diff
@@ -118,9 +133,9 @@ Shader::Shader(Shader &&rhs) : id_{rhs.id_}, ready_(rhs.ready_), warningLevel_{r
 Shader &Shader::operator=(const Shader &that) {
     if (this != &that) {
         bool needRegister = false;
-        if (id_ == 0) {
+        if (!prog_.created()) {
             needRegister = true;
-            id_ = glCreateProgram();
+            prog_.id = glCreateProgram();
```
Comment (petersteneteg) [inline modules/opengl/src/shader/shader.cpp]: Same here, this is leaking encapsulation...

File: modules/opengl/src/shader/shader.cpp (hunk 5 above)
Comment (ResearchDaniel) [reply modules/opengl/src/shader/shader.cpp]: Not possible since we need to deregister the rhs shader as far as I understood. This applies in a couple of situations where it is not possible to do something without knowing about the shader (assignment). I therefore tried to keep the ScopedShaderProgram as light-weight as possible

File: modules/opengl/src/shader/shader.cpp (hunk 6 above)
Comment (ResearchDaniel) [reply modules/opengl/src/shader/shader.cpp]: Same reasoning here, the ScopedShaderProgram is just responsible for scoping, not other parts since I could not find a good way of moving all responsibilities to it...

Comment (petersteneteg) [reply modules/opengl/src/shader/shader.cpp]: That kind of shared responsibility does not look like a very attractive pattern...

Comment (ResearchDaniel) [reply modules/opengl/src/shader/shader.cpp]: Agree, but I think it would require quite some changes otherwise. Handing over a reference to the shader would possibly resolve it but that is also quite ugly. Happy to take suggestions on how to resolve it in a better way.

File: modules/opengl/src/shader/shader.cpp (hunk 1 above)
Comment (martinfalk) [reply modules/opengl/src/shader/shader.cpp]: yes, I think so, too.

**Review by martinfalk — APPROVED** [review]

File: modules/opengl/src/shader/shader.cpp (hunk 6 above)
Comment (petersteneteg) [reply modules/opengl/src/shader/shader.cpp]: Let me have a look on this...

Comment (petersteneteg) [reply modules/opengl/src/shader/shader.cpp]: Easiest way would have been to just check for the vertex shader, before ever creating the program..

**Review by petersteneteg — DISMISSED** [review]
This need more work

File: modules/opengl/include/modules/opengl/shader/standardshaders.h [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+#include <inviwo/core/common/inviwo.h>
+
+#include <modules/opengl/shader/shaderresource.h>
+#include <modules/opengl/shader/shadertype.h>
+
+namespace inviwo {
+
+namespace utilgl {
+
+IVW_MODULE_OPENGL_API std::pair<ShaderType, std::shared_ptr<const ShaderResource>> imgQuadVert();
```
Comment (ResearchDaniel) [inline modules/opengl/include/modules/opengl/shader/standardshaders.h]: Should document what this one does. Provide the shader as documentation?
Would also rename it to imgQuadVertexShader(), possibly even adding create, i.e., createImgQuadVertexShader

File: modules/opengl/include/modules/opengl/shader/standardshaders.h [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+
+IVW_MODULE_OPENGL_API std::pair<ShaderType, std::shared_ptr<const ShaderResource>>
+imgIdentityVert();
```
Comment (ResearchDaniel) [inline modules/opengl/include/modules/opengl/shader/standardshaders.h:45]: Same here, document what it does and possibly rename

File: modules/opengl/src/shader/standardshaders.cpp [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+
+#include <modules/opengl/shader/standardshaders.h>
+
+namespace inviwo {
+
+namespace utilgl {
+std::pair<ShaderType, std::shared_ptr<const ShaderResource>> imgQuadVert() {
+    static const std::shared_ptr<const ShaderResource> vert =
+        std::make_shared<StringShaderResource>("image_quad.vert", R"(
+out vec3 texCoord_;
```
Comment (ResearchDaniel) [inline modules/opengl/src/shader/standardshaders.cpp:40]: indent missing?

**Review by ResearchDaniel — COMMENTED** [review]
Looks good. I would add some comments about the shaders and maybe rename them to be a bit clearer

File: modules/opengl/src/shader/standardshaders.cpp (hunk 9 above)
Comment (petersteneteg) [reply modules/opengl/src/shader/standardshaders.cpp:40]: No, using raw strings, here so no indent...

File: modules/opengl/include/modules/opengl/shader/standardshaders.h (hunk 7 above)
Comment (petersteneteg) [reply modules/opengl/include/modules/opengl/shader/standardshaders.h]: So its only a string shader resource, not a shaderobject, or even a shader. Hence it never creates anything, just returns the string data...

Comment (petersteneteg) [reply modules/opengl/include/modules/opengl/shader/standardshaders.h]: the do the same thing as the img_identity.vert and img_texturequad.vert... which has not further explanation.

File: modules/opengl/include/modules/opengl/shader/standardshaders.h (hunk 8 above)
Comment (petersteneteg) [reply modules/opengl/include/modules/opengl/shader/standardshaders.h:45]: added short desc

File: modules/opengl/include/modules/opengl/shader/standardshaders.h (hunk 7 above)
Comment (ResearchDaniel) [reply modules/opengl/include/modules/opengl/shader/standardshaders.h]: Would just be nice to be able to understand what they do without going to the source. This could be done by just copying in the shader code in the documentation. No major issue
