### PR TITLE
OIT: rasterizer validation, #1585

### LINKED ISSUE #1585: [BUG]: Brushing and Linking broken in `SphereRasterizer`
### Required prerequisites

- [X] Make sure you've read the [documentation](https://inviwo.org). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/inviwo/inviwo/issues) and [Discussions](https://github.com/inviwo/inviwo/discussionss) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in [Slack](https://join.slack.com/t/inviwo/shared_invite/enQtNTc2Nzc2NDQwNzIxLTRiMWM1ZWJiYjljZjkwNWE3OTk3MzYxODZlMDUyMzRmZjUzMzBiZjVhNTM3NWUyNzU1MjI4OWJjMzdkODViMzM) or in a [Discussion](https://github.com/inviwo/inviwo/discussionss).

### Problem description

Brushing and Linking in the `Sphere Rasterizer` and `Sphere Renderer` is handled by [`MeshBnLGL`](https://github.com/inviwo/inviwo/blob/master/modules/basegl/include/modules/basegl/util/meshbnlgl.h). 
`MeshBnLGL::update()` relies on `BrushingAndLinkingInport::isChanged()` and `isModified()`. 

https://github.com/inviwo/inviwo/blob/31397844d455259ae9455abdb4bacab603b41b77/modules/basegl/src/util/meshbnlgl.cpp#L50-L53

The problem is that the rasterization delays the evaluation of these functions to the `Rasterization Renderer` after the rasterizer processor was processed, and in turn the invalidation/changed state of the B&L manager and associated properties was reset. Thus, `MeshBnLGL::update()` never updates the internal state.

### Inviwo version

3139784

### Operating system?

_No response_

### Compiler / Version

_No response_

### Qt Version

_No response_

### Reproducible example code

```text
1. Set up `Sphere Rasterizer` and `Rasterization Renderer` network.
2. Add breakpoint in meshbnlgl.cpp:52
3. Change one of the `Enable Selection/Highlight/Filtering` properties
4. on break, check `isModified` states of properties.
```

### Inviwo log

_No response_

### PR DESCRIPTION
**Pull request by martinfalk**
* Rasterizer inports and properties may be evaluated during rasterization

Fixes #1585 

Changes proposed in this PR:
 * delay Rasterizer validation

### CODE REVIEW

File: modules/oit/src/processors/rasterizationrenderer.cpp [hunk 1]
```diff
@@ -240,6 +240,13 @@ void RasterizationRenderer::process() {
     }
 
     utilgl::deactivateCurrentTarget();
+
+    // Set rasterization processors to valid now that rasterization is done and properties/inports
+    // were used.
+    // @see Rasterization::setValid()
+    for (auto rasterization : rasterizations_) {
+        rasterization->getProcessor()->Processor::setValid();
```
Comment (petersteneteg) [inline modules/oit/src/processors/rasterizationrenderer.cpp]: This should work, But I think adding a new function like "setValidDelayed" in the rasterizer base, and calling that might be a bit clearer.

**Review by petersteneteg — DISMISSED** [review]

File: modules/oit/src/processors/rasterizationrenderer.cpp (hunk 1 above)
Comment (martinfalk) [reply modules/oit/src/processors/rasterizationrenderer.cpp]: Good idea. Was even considering that.

**Review by petersteneteg — APPROVED** [review]

**Review by petersteneteg — APPROVED** [review]
