### PR TITLE
Linkfix

### LINKED ISSUE #494: Linking broken for OrdinalProperty
Linked ordinal properties are not synchronized **if only the maximum** of one property is changed (`OrdinalProperty::setMax()`).

Changing the value afterward also updates the new bounds.

### PR DESCRIPTION
**Pull request by petersteneteg**
Core: Ordinal and MinMax Properties fixes for linking. closes #494

### CODE REVIEW

**Review by r-englund — APPROVED** [review]

File: include/inviwo/core/properties/minmaxproperty.h [hunk 1]
```diff
@@ -115,15 +115,13 @@ class MinMaxProperty : public TemplateProperty<glm::tvec2<T, glm::defaultp>> {
...
-     * @return returns the pair { modified, valid value } where modified indicates
-     *            whether the given value was adjusted. The new value is stored as
-     *            second parameter. In case there was not modification, valid value
-     *            is equal to TemplateProperty<range_type>::value_.
+     * @param v   value to be clamped
+     * @return returns a valid value within the min max range
      */
-    auto validateValues(const range_type& v) -> std::pair<bool, range_type>;
+    range_type clamp(const range_type& v) const;
+    T limitSeperation(T sep) const;
```
Comment (ResearchDaniel) [inline include/inviwo/core/properties/minmaxproperty.h]: typo -> limitSeparation

**Review by ResearchDaniel — APPROVED** [review]
Nice, saw minor type

File: modules/hdf5/src/processors/hdf5volumesource.cpp [hunk 2]
```diff
@@ -62,7 +62,7 @@ HDF5ToVolume::HDF5ToVolume()
 
     , basisGroup_("basisGroup", "Basis")
     , basisSelection_("basisSelection", "Source")
-    , basis_("basis", "Matrix", mat4(1.0f), mat4(-10.0f), mat4(10.0))
+    , basis_("basis", "Matrix", mat4(1.0f), mat4(-1000.0f), mat4(1000.0))
```
Comment (r-englund) [inline modules/hdf5/src/processors/hdf5volumesource.cpp]: this will make min and max be diagonal matrices, use `util::filled<mat4>(1000.f)` (https://github.com/inviwo/inviwo/blob/master/include/inviwo/core/util/glm.h#L815-L828)
