### PR TITLE
Feature/fix static builds windows

### LINKED ISSUE #10: Static build broken on Windows
Getting unresolved errors when linking inviwo/inviwo-cli, cant find __imp__glfwBindBuffer  etc

### PR DESCRIPTION
**Pull request by r-englund**
Some fixes to enable static building on windows. 
Closes #10

### CODE REVIEW

File: include/inviwo/core/properties/tfpropertyconcept.h [hunk 1]
```diff
@@ -162,7 +162,8 @@ IVW_CORE_API const dvec2 TFPropertyModel<IsoValueProperty*>::getMaskInternal() c
 template <>
 IVW_CORE_API void TFPropertyModel<IsoValueProperty*>::clearMaskInternal();
 
-template IVW_CORE_API class TFPropertyModel<IsoValueProperty*>;
+//template IVW_CORE_API class TFPropertyModel<IsoValueProperty*>;
```
Comment (ResearchDaniel) [inline include/inviwo/core/properties/tfpropertyconcept.h]: remove

File: include/inviwo/core/properties/tfpropertyconcept.h [hunk 2]
```diff
@@ -177,7 +178,8 @@ template <>
 IVW_CORE_API TransferFunctionProperty* TFPropertyModel<IsoTFProperty*>::getTFPropertyInternal()
     const;
 
-template IVW_CORE_API class TFPropertyModel<IsoTFProperty*>;
+//template IVW_CORE_API class TFPropertyModel<IsoTFProperty*>;
```
Comment (ResearchDaniel) [inline include/inviwo/core/properties/tfpropertyconcept.h]: Remove

**Review by ResearchDaniel — APPROVED** [review]
Remove commented code

**Review by ResearchDaniel — APPROVED** [review]

**Review by petersteneteg — APPROVED** [review]
