### PR TITLE
Clang extern template fixes

### LINKED ISSUE #222: Animation module compile error in XCode
Get the following compile error in XCode:

> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:4333:13: No matching function for call to object of type 'std::__1::__less<std::__1::chrono::duration<double, std::__1::ratio<1, 1> >, inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<glm::vec<3, float, glm::qualifier::packed_highp> > > &>'

The error seem to appear on all instantiations of KeyFrameSequenceTyped. From what I can see the operator< is implemented for KeyFrameSequence. Any idea on how to resolve?

**Environment information**
* Operating System: Mac
* Compiler/IDE: LLVM 9.0/Xcode

Log:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:4333:13: No matching function for call to object of type 'std::__1::__less<std::__1::chrono::duration<double, std::__1::ratio<1, 1> >, inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > &>'
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/animationmodule.cpp:30:10: In file included from /Users/danieljonsson/Documents/inviwo/dev/modules/animation/animationmodule.cpp:30:
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/animationmodule.h:34:10: In file included from /Users/danieljonsson/Documents/inviwo/dev/modules/animation/animationmodule.h:34:
/Users/danieljonsson/Documents/inviwo/dev/include/inviwo/core/common/inviwomodule.h:33:10: In file included from /Users/danieljonsson/Documents/inviwo/dev/include/inviwo/core/common/inviwomodule.h:33:
/Users/danieljonsson/Documents/inviwo/dev/include/inviwo/core/common/inviwo.h:54:10: In file included from /Users/danieljonsson/Documents/inviwo/dev/include/inviwo/core/common/inviwo.h:54:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:10: In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iostream:38:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:10: In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ios:216:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:15:10: In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__locale:15:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:10: In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:470:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:10: In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:169:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:10: In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:4355:12: In instantiation of function template specialization 'std::__1::__upper_bound<std::__1::__less<std::__1::chrono::duration<double, std::__1::ratio<1, 1> >, inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > &> &, inviwo::util::IndirectIterator<std::__1::__wrap_iter<const std::__1::unique_ptr<inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> >, std::__1::default_delete<inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > > > *>, true>, std::__1::chrono::duration<double, std::__1::ratio<1, 1> > >' requested here
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:4364:19: In instantiation of function template specialization 'std::__1::upper_bound<inviwo::util::IndirectIterator<std::__1::__wrap_iter<const std::__1::unique_ptr<inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> >, std::__1::default_delete<inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > > > *>, true>, std::__1::chrono::duration<double, std::__1::ratio<1, 1> >, std::__1::__less<std::__1::chrono::duration<double, std::__1::ratio<1, 1> >, inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > &> >' requested here
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/datastructures/propertytrack.h:320:20: In instantiation of function template specialization 'std::__1::upper_bound<inviwo::util::IndirectIterator<std::__1::__wrap_iter<const std::__1::unique_ptr<inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> >, std::__1::default_delete<inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > > > *>, true>, std::__1::chrono::duration<double, std::__1::ratio<1, 1> > >' requested here
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/datastructures/propertytrack.h:172:5: In instantiation of member function 'inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> >::operator()' requested here
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3032:32: In instantiation of member function 'inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> >::PropertyTrack' requested here
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/factories/trackfactoryobject.h:63:74: In instantiation of function template specialization 'std::__1::make_unique<inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> >>' requested here
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/factories/trackfactoryobject.h:57:5: In instantiation of member function 'inviwo::animation::TrackFactoryObjectTemplate<inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> > >::create' requested here
/Users/danieljonsson/Documents/inviwo/dev/include/inviwo/core/util/stdextensions.h:58:35: In instantiation of member function 'inviwo::animation::TrackFactoryObjectTemplate<inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> > >::TrackFactoryObjectTemplate' requested here
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/animationsupplier.h:111:24: In instantiation of function template specialization 'inviwo::util::make_unique<inviwo::animation::TrackFactoryObjectTemplate<inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> > >>' requested here
/Users/danieljonsson/Documents/inviwo/dev/modules/animation/animationmodule.cpp:54:8: In instantiation of function template specialization 'inviwo::animation::AnimationSupplier::registerTrack<inviwo::animation::PropertyTrack<inviwo::OrdinalProperty<unsigned int>, inviwo::animation::ValueKeyframe<unsigned int> > >' requested here
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:703:10: Candidate function not viable: no known conversion from 'const inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> >' to 'const std::__1::chrono::duration<double, std::__1::ratio<1, 1> >' for 2nd argument
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:706:10: Candidate function not viable: 2nd argument ('const inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> >') would lose const qualifier
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:709:10: Candidate function not viable: no known conversion from 'const std::__1::chrono::duration<double, std::__1::ratio<1, 1> >' to 'inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > &&' for 1st argument
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:712:10: Candidate function not viable: no known conversion from 'const std::__1::chrono::duration<double, std::__1::ratio<1, 1> >' to 'inviwo::animation::KeyframeSequenceTyped<inviwo::animation::ValueKeyframe<unsigned int> > &&' for 1st argument

### PR DESCRIPTION
**Pull request by petersteneteg**
And some warning fixes

fixes #222

### CODE REVIEW

File: include/inviwo/core/common/inviwocoredefine.h [hunk 1]
```diff
@@ -36,22 +36,32 @@
         #ifdef _WIN32
             #define IVW_CORE_API __declspec(dllexport)
             #define IVW_CORE_EXT
+            #define IVW_CORE_TMPL_EXP
```
Comment (ResearchDaniel) [inline include/inviwo/core/common/inviwocoredefine.h:39]: Now that we have so many of these defines it would be good on an explanation when to use which :)

File: include/inviwo/core/properties/optionproperty.h [hunk 2]
```diff
@@ -140,10 +131,10 @@ class TemplateOptionProperty : public BaseOptionProperty {
                            InvalidationLevel invalidationLevel = InvalidationLevel::InvalidOutput,
                            PropertySemantics semantics = PropertySemantics::Default);
 
-    TemplateOptionProperty(const TemplateOptionProperty<T>& rhs) = default;
-    TemplateOptionProperty<T>& operator=(const TemplateOptionProperty<T>& that) = default;
+    TemplateOptionProperty(const TemplateOptionProperty<T>& rhs);
+    TemplateOptionProperty<T>& operator=(const TemplateOptionProperty<T>& that);
     virtual TemplateOptionProperty<T>* clone() const override;
-    virtual ~TemplateOptionProperty() = default;
```
Comment (ResearchDaniel) [inline include/inviwo/core/properties/optionproperty.h:146]: Not possible to use this for templates if we want to export some of them?

**Review by ResearchDaniel — APPROVED** [review]
Now works on my mac 👍 
It would be nice with an explanation of when to use the new defines

File: include/inviwo/core/properties/optionproperty.h (hunk 2 above)
Comment (petersteneteg) [reply include/inviwo/core/properties/optionproperty.h:146]: There seems to be issues on Msvc when exporeing defaulted in class definitions, out of class defaulted definitions seems to work. Only saw that error for the assignment operator, but took the safe approch and defined them all out of class

File: include/inviwo/core/common/inviwocoredefine.h (hunk 1 above)
Comment (petersteneteg) [reply include/inviwo/core/common/inviwocoredefine.h:39]: True, still not quite sure what is the "official" way of solving this... libc++ has lots and lots of these... if this seems to work out maybe we can try and explain it...
